[phases.setup]
aptPkgs = ["tesseract-ocr", "tesseract-ocr-fra", "tesseract-ocr-eng"]
nixPkgs = ["python311"]

[phases.install]
cmds = ["cd backend && pip install -r requirements.txt"]

[start]
cmd = "cd backend && uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000}"
